spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentdb?useSSL=false
    username: root
    password: OmgPassword!
  sql:
    init:
      mode: always
      
 
 